version: 2
jobs:
  fetch_and_commit:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            cp dams.csv dams-old.csv
            sudo pip install csv-diff pandas xlrd
            python fetch_dams_csv.py
            git add dams.csv
            git config --global user.email "damsbot@example.com"
            git config --global user.name "Damsbot"
            csv-diff dams-old.csv dams.csv --key=RECORDID > message.txt
            git commit -F message.txt && \
              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/simonw/us-dams-history.git master \
              || true

workflows:
  version: 2
  build:
    jobs:
      - fetch_and_commit
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - fetch_and_commit
